export const countries = [
    { name: "Afganistan", name_en: "Afghanistan", code: "AF" },
    { name: "Albania", name_en: "Albania", code: "AL" },
    { name: "Algieria", name_en: "Algeria", code: "DZ" },
    { name: "Andora", name_en: "Andorra", code: "AD" },
    { name: "Angola", name_en: "Angola", code: "AO" },
    { name: "Anguilla", name_en: "Anguilla", code: "AI" },
    { name: "Antarktyka", name_en: "Antarctica", code: "AQ" },
    {
        name: "Antigua i Barbuda",
        name_en: "Antigua and Barbuda",
        code: "AG",
    },
    { name: "Arabia Saudyjska", name_en: "Saudi Arabia", code: "SA" },
    { name: "Argentyna", name_en: "Argentina", code: "AR" },
    { name: "Armenia", name_en: "Armenia", code: "AM" },
    { name: "Aruba", name_en: "Aruba", code: "AW" },
    { name: "Australia", name_en: "Australia", code: "AU" },
    { name: "Austria", name_en: "Austria", code: "AT" },
    { name: "Azerbejdżan", name_en: "Azerbaijan", code: "AZ" },
    { name: "Bahamy", name_en: "Bahamas", code: "BS" },
    { name: "Bahrajn", name_en: "Bahrain", code: "BH" },
    { name: "Bangladesz", name_en: "Bangladesh", code: "BD" },
    { name: "Barbados", name_en: "Barbados", code: "BB" },
    { name: "Belgia", name_en: "Belgium", code: "BE" },
    { name: "Belize", name_en: "Belize", code: "BZ" },
    { name: "Benin", name_en: "Benin", code: "BJ" },
    { name: "Bermudy", name_en: "Bermuda", code: "BM" },
    { name: "Bhutan", name_en: "Bhutan", code: "BT" },
    { name: "Białoruś", name_en: "Belarus", code: "BY" },
    {
        name: "Boliwia",
        name_en: "Bolivia, Plurinational State of",
        code: "BO",
    },
    {
        name: "Bonaire, Sint Eustatius i Saba",
        name_en: "Bonaire, Sint Eustatius and Saba",
        code: "BQ",
    },
    {
        name: "Bośnia i Hercegowina",
        name_en: "Bosnia and Herzegovina",
        code: "BA",
    },
    { name: "Botswana", name_en: "Botswana", code: "BW" },
    { name: "Brazylia", name_en: "Brazil", code: "BR" },
    { name: "Brunei", name_en: "Brunei Darussalam", code: "BN" },
    {
        name: "Brytyjskie Terytorium Oceanu Indyjskiego",
        name_en: "British Indian Ocean Territory",
        code: "IO",
    },
    {
        name: "Brytyjskie Wyspy Dziewicze",
        name_en: "Virgin Islands, British",
        code: "VG",
    },
    { name: "Bułgaria", name_en: "Bulgaria", code: "BG" },
    { name: "Burkina Faso", name_en: "Burkina Faso", code: "BF" },
    { name: "Burundi", name_en: "Burundi", code: "BI" },
    { name: "Chile", name_en: "Chile", code: "CL" },
    { name: "Chiny", name_en: "China", code: "CN" },
    { name: "Chorwacja", name_en: "Croatia", code: "HR" },
    { name: "Curaçao", name_en: "Curaçao", code: "CW" },
    { name: "Cypr", name_en: "Cyprus", code: "CY" },
    { name: "Czad", name_en: "Chad", code: "TD" },
    { name: "Czarnogóra", name_en: "Montenegro", code: "ME" },
    { name: "Czechy", name_en: "Czech Republic", code: "CZ" },
    {
        name: "Dalekie Wyspy Mniejsze Stanów Zjednoczonych",
        name_en: "United States Minor Outlying Islands",
        code: "UM",
    },
    { name: "Dania", name_en: "Denmark", code: "DK" },
    {
        name: "Demokratyczna Republika Konga",
        name_en: "Congo, the Democratic Republic of the",
        code: "CD",
    },
    { name: "Dominika", name_en: "Dominica", code: "DM" },
    { name: "Dominikana", name_en: "Dominican Republic", code: "DO" },
    { name: "Dżibuti", name_en: "Djibouti", code: "DJ" },
    { name: "Egipt", name_en: "Egypt", code: "EG" },
    { name: "Ekwador", name_en: "Ecuador", code: "EC" },
    { name: "Erytrea", name_en: "Eritrea", code: "ER" },
    { name: "Estonia", name_en: "Estonia", code: "EE" },
    { name: "Etiopia", name_en: "Ethiopia", code: "ET" },
    {
        name: "Falklandy",
        name_en: "Falkland Islands (Malvinas)",
        code: "FK",
    },
    { name: "Fidżi", name_en: "Fiji", code: "FJ" },
    { name: "Filipiny", name_en: "Philippines", code: "PH" },
    { name: "Finlandia", name_en: "Finland", code: "FI" },
    { name: "Francja", name_en: "France", code: "FR" },
    {
        name: "Francuskie Terytoria Południowe i Antarktyczne",
        name_en: "French Southern Territories",
        code: "TF",
    },
    { name: "Gabon", name_en: "Gabon", code: "GA" },
    { name: "Gambia", name_en: "Gambia", code: "GM" },
    {
        name: "Georgia Południowa i Sandwich Południowy",
        name_en: "South Georgia and the South Sandwich Islands",
        code: "GS",
    },
    { name: "Ghana", name_en: "Ghana", code: "GH" },
    { name: "Gibraltar", name_en: "Gibraltar", code: "GI" },
    { name: "Grecja", name_en: "Greece", code: "GR" },
    { name: "Grenada", name_en: "Grenada", code: "GD" },
    { name: "Grenlandia", name_en: "Greenland", code: "GL" },
    { name: "Gruzja", name_en: "Georgia", code: "GE" },
    { name: "Guam", name_en: "Guam", code: "GU" },
    { name: "Guernsey", name_en: "Guernsey", code: "GG" },
    { name: "Gujana Francuska", name_en: "French Guiana", code: "GF" },
    { name: "Gujana", name_en: "Guyana", code: "GY" },
    { name: "Gwadelupa", name_en: "Guadeloupe", code: "GP" },
    { name: "Gwatemala", name_en: "Guatemala", code: "GT" },
    { name: "Gwinea Bissau", name_en: "Guinea-Bissau", code: "GW" },
    { name: "Gwinea Równikowa", name_en: "Equatorial Guinea", code: "GQ" },
    { name: "Gwinea", name_en: "Guinea", code: "GN" },
    { name: "Haiti", name_en: "Haiti", code: "HT" },
    { name: "Hiszpania", name_en: "Spain", code: "ES" },
    { name: "Holandia", name_en: "Netherlands", code: "NL" },
    { name: "Honduras", name_en: "Honduras", code: "HN" },
    { name: "Hongkong", name_en: "Hong Kong", code: "HK" },
    { name: "Indie", name_en: "India", code: "IN" },
    { name: "Indonezja", name_en: "Indonesia", code: "ID" },
    { name: "Irak", name_en: "Iraq", code: "IQ" },
    { name: "Iran", name_en: "Iran, Islamic Republic of", code: "IR" },
    { name: "Irlandia", name_en: "Ireland", code: "IE" },
    { name: "Islandia", name_en: "Iceland", code: "IS" },
    { name: "Izrael", name_en: "Israel", code: "IL" },
    { name: "Jamajka", name_en: "Jamaica", code: "JM" },
    { name: "Japonia", name_en: "Japan", code: "JP" },
    { name: "Jemen", name_en: "Yemen", code: "YE" },
    { name: "Jersey", name_en: "Jersey", code: "JE" },
    { name: "Jordania", name_en: "Jordan", code: "JO" },
    { name: "Kajmany", name_en: "Cayman Islands", code: "KY" },
    { name: "Kambodża", name_en: "Cambodia", code: "KH" },
    { name: "Kamerun", name_en: "Cameroon", code: "CM" },
    { name: "Kanada", name_en: "Canada", code: "CA" },
    { name: "Katar", name_en: "Qatar", code: "QA" },
    { name: "Kazachstan", name_en: "Kazakhstan", code: "KZ" },
    { name: "Kenia", name_en: "Kenya", code: "KE" },
    { name: "Kirgistan", name_en: "Kyrgyzstan", code: "KG" },
    { name: "Kiribati", name_en: "Kiribati", code: "KI" },
    { name: "Kolumbia", name_en: "Colombia", code: "CO" },
    { name: "Komory", name_en: "Comoros", code: "KM" },
    { name: "Kongo", name_en: "Congo", code: "CG" },
    { name: "Korea Południowa", name_en: "Korea, Republic of", code: "KR" },
    {
        name: "Korea Północna",
        name_en: "Korea, Democratic People's Republic of",
        code: "KP",
    },
    { name: "Kostaryka", name_en: "Costa Rica", code: "CR" },
    { name: "Kuba", name_en: "Cuba", code: "CU" },
    { name: "Kuwejt", name_en: "Kuwait", code: "KW" },
    {
        name: "Laos",
        name_en: "Lao People's Democratic Republic",
        code: "LA",
    },
    { name: "Lesotho", name_en: "Lesotho", code: "LS" },
    { name: "Liban", name_en: "Lebanon", code: "LB" },
    { name: "Liberia", name_en: "Liberia", code: "LR" },
    { name: "Libia", name_en: "Libyan Arab Jamahiriya", code: "LY" },
    { name: "Liechtenstein", name_en: "Liechtenstein", code: "LI" },
    { name: "Litwa", name_en: "Lithuania", code: "LT" },
    { name: "Luksemburg", name_en: "Luxembourg", code: "LU" },
    { name: "Łotwa", name_en: "Latvia", code: "LV" },
    {
        name: "Macedonia",
        name_en: "Macedonia, the former Yugoslav Republic of",
        code: "MK",
    },
    { name: "Madagaskar", name_en: "Madagascar", code: "MG" },
    { name: "Majotta", name_en: "Mayotte", code: "YT" },
    { name: "Makau", name_en: "Macao", code: "MO" },
    { name: "Malawi", name_en: "Malawi", code: "MW" },
    { name: "Malediwy", name_en: "Maldives", code: "MV" },
    { name: "Malezja", name_en: "Malaysia", code: "MY" },
    { name: "Mali", name_en: "Mali", code: "ML" },
    { name: "Malta", name_en: "Malta", code: "MT" },
    {
        name: "Mariany Północne",
        name_en: "Northern Mariana Islands",
        code: "MP",
    },
    { name: "Maroko", name_en: "Morocco", code: "MA" },
    { name: "Martynika", name_en: "Martinique", code: "MQ" },
    { name: "Mauretania", name_en: "Mauritania", code: "MR" },
    { name: "Mauritius", name_en: "Mauritius", code: "MU" },
    { name: "Meksyk", name_en: "Mexico", code: "MX" },
    {
        name: "Mikronezja",
        name_en: "Micronesia, Federated States of",
        code: "FM",
    },
    { name: "Mjanma", name_en: "Myanmar", code: "MM" },
    { name: "Mołdawia", name_en: "Moldova, Republic of", code: "MD" },
    { name: "Monako", name_en: "Monaco", code: "MC" },
    { name: "Mongolia", name_en: "Mongolia", code: "MN" },
    { name: "Montserrat", name_en: "Montserrat", code: "MS" },
    { name: "Mozambik", name_en: "Mozambique", code: "MZ" },
    { name: "Namibia", name_en: "Namibia", code: "NA" },
    { name: "Nauru", name_en: "Nauru", code: "NR" },
    { name: "Nepal", name_en: "Nepal", code: "NP" },
    { name: "Niemcy", name_en: "Germany", code: "DE" },
    { name: "Niger", name_en: "Niger", code: "NE" },
    { name: "Nigeria", name_en: "Nigeria", code: "NG" },
    { name: "Nikaragua", name_en: "Nicaragua", code: "NI" },
    { name: "Niue", name_en: "Niue", code: "NU" },
    { name: "Norfolk", name_en: "Norfolk Island", code: "NF" },
    { name: "Norwegia", name_en: "Norway", code: "NO" },
    { name: "Nowa Kaledonia", name_en: "New Caledonia", code: "NC" },
    { name: "Nowa Zelandia", name_en: "New Zealand", code: "NZ" },
    { name: "Oman", name_en: "Oman", code: "OM" },
    { name: "Pakistan", name_en: "Pakistan", code: "PK" },
    { name: "Palau", name_en: "Palau", code: "PW" },
    {
        name: "Palestyna",
        name_en: "Palestinian Territory, Occupied",
        code: "PS",
    },
    { name: "Panama", name_en: "Panama", code: "PA" },
    { name: "Papua-Nowa Gwinea", name_en: "Papua New Guinea", code: "PG" },
    { name: "Paragwaj", name_en: "Paraguay", code: "PY" },
    { name: "Peru", name_en: "Peru", code: "PE" },
    { name: "Pitcairn", name_en: "Pitcairn", code: "PN" },
    { name: "Polinezja Francuska", name_en: "French Polynesia", code: "PF" },
    { name: "Polska", name_en: "Poland", code: "PL" },
    { name: "Portoryko", name_en: "Puerto Rico", code: "PR" },
    { name: "Portugalia", name_en: "Portugal", code: "PT" },
    {
        name: "Republika Południowej Afryki",
        name_en: "South Africa",
        code: "ZA",
    },
    {
        name: "Republika Środkowoafrykańska",
        name_en: "Central African Republic",
        code: "CF",
    },
    {
        name: "Republika Zielonego Przylądka",
        name_en: "Cape Verde",
        code: "CV",
    },
    { name: "Reunion", name_en: "Réunion", code: "RE" },
    { name: "Rosja", name_en: "Russian Federation", code: "RU" },
    { name: "Rumunia", name_en: "Romania", code: "RO" },
    { name: "Rwanda", name_en: "Rwanda", code: "RW" },
    { name: "Sahara Zachodnia", name_en: "Western Sahara", code: "EH" },
    {
        name: "Saint Kitts i Nevis",
        name_en: "Saint Kitts and Nevis",
        code: "KN",
    },
    { name: "Saint Lucia", name_en: "Saint Lucia", code: "LC" },
    {
        name: "Saint Vincent i Grenadyny",
        name_en: "Saint Vincent and the Grenadines",
        code: "VC",
    },
    { name: "Saint-Barthélemy", name_en: "Saint Barthélemy", code: "BL" },
    {
        name: "Saint-Martin",
        name_en: "Saint Martin (French part)",
        code: "MF",
    },
    {
        name: "Saint-Pierre i Miquelon",
        name_en: "Saint Pierre and Miquelon",
        code: "PM",
    },
    { name: "Salwador", name_en: "El Salvador", code: "SV" },
    { name: "Samoa Amerykańskie", name_en: "American Samoa", code: "AS" },
    { name: "Samoa", name_en: "Samoa", code: "WS" },
    { name: "San Marino", name_en: "San Marino", code: "SM" },
    { name: "Senegal", name_en: "Senegal", code: "SN" },
    { name: "Serbia", name_en: "Serbia", code: "RS" },
    { name: "Seszele", name_en: "Seychelles", code: "SC" },
    { name: "Sierra Leone", name_en: "Sierra Leone", code: "SL" },
    { name: "Singapur", name_en: "Singapore", code: "SG" },
    {
        name: "Sint Maarten",
        name_en: "Sint Maarten (Dutch part)",
        code: "SX",
    },
    { name: "Słowacja", name_en: "Slovakia", code: "SK" },
    { name: "Słowenia", name_en: "Slovenia", code: "SI" },
    { name: "Somalia", name_en: "Somalia", code: "SO" },
    { name: "Sri Lanka", name_en: "Sri Lanka", code: "LK" },
    { name: "Stany Zjednoczone", name_en: "United States", code: "US" },
    { name: "Suazi", name_en: "Swaziland", code: "SZ" },
    { name: "Sudan", name_en: "Sudan", code: "SD" },
    { name: "Sudan Południowy", name_en: "South Sudan", code: "SS" },
    { name: "Surinam", name_en: "Suriname", code: "SR" },
    {
        name: "Svalbard i Jan Mayen",
        name_en: "Svalbard and Jan Mayen",
        code: "SJ",
    },
    { name: "Syria", name_en: "Syrian Arab Republic", code: "SY" },
    { name: "Szwajcaria", name_en: "Switzerland", code: "CH" },
    { name: "Szwecja", name_en: "Sweden", code: "SE" },
    { name: "Tadżykistan", name_en: "Tajikistan", code: "TJ" },
    { name: "Tajlandia", name_en: "Thailand", code: "TH" },
    { name: "Tajwan", name_en: "Taiwan, Province of China", code: "TW" },
    {
        name: "Tanzania",
        name_en: "Tanzania, United Republic of",
        code: "TZ",
    },
    { name: "Timor Wschodni", name_en: "Timor-Leste", code: "TL" },
    { name: "Togo", name_en: "Togo", code: "TG" },
    { name: "Tokelau", name_en: "Tokelau", code: "TK" },
    { name: "Tonga", name_en: "Tonga", code: "TO" },
    {
        name: "Trynidad i Tobago",
        name_en: "Trinidad and Tobago",
        code: "TT",
    },
    { name: "Tunezja", name_en: "Tunisia", code: "TN" },
    { name: "Turcja", name_en: "Turkey", code: "TR" },
    { name: "Turkmenistan", name_en: "Turkmenistan", code: "TM" },
    {
        name: "Turks i Caicos",
        name_en: "Turks and Caicos Islands",
        code: "TC",
    },
    { name: "Tuvalu", name_en: "Tuvalu", code: "TV" },
    { name: "Uganda", name_en: "Uganda", code: "UG" },
    { name: "Ukraina", name_en: "Ukraine", code: "UA" },
    { name: "Urugwaj", name_en: "Uruguay", code: "UY" },
    { name: "Uzbekistan", name_en: "Uzbekistan", code: "UZ" },
    { name: "Vanuatu", name_en: "Vanuatu", code: "VU" },
    { name: "Wallis i Futuna", name_en: "Wallis and Futuna", code: "WF" },
    {
        name: "Watykan",
        name_en: "Holy See (Vatican City State)",
        code: "VA",
    },
    {
        name: "Wenezuela",
        name_en: "Venezuela, Bolivarian Republic of",
        code: "VE",
    },
    { name: "Węgry", name_en: "Hungary", code: "HU" },
    { name: "Wielka Brytania", name_en: "United Kingdom", code: "GB" },
    { name: "Wietnam", name_en: "Viet Nam", code: "VN" },
    { name: "Włochy", name_en: "Italy", code: "IT" },
    {
        name: "Wybrzeże Kości Słoniowej",
        name_en: "Côte d'Ivoire",
        code: "CI",
    },
    { name: "Wyspa Bouveta", name_en: "Bouvet Island", code: "BV" },
    {
        name: "Wyspa Bożego Narodzenia",
        name_en: "Christmas Island",
        code: "CX",
    },
    { name: "Wyspa Man", name_en: "Isle of Man", code: "IM" },
    {
        name: "Wyspa Świętej Heleny, Wyspa Wniebowstąpienia i Tristan da Cunha",
        name_en: "Saint Helena, Ascension and Tristan Cunha",
        code: "SH",
    },
    { name: "Wyspy Alandzkie", name_en: "Åland Islands", code: "AX" },
    { name: "Wyspy Cooka", name_en: "Cook Islands", code: "CK" },
    {
        name: "Wyspy Dziewicze Stanów Zjednoczonych",
        name_en: "Virgin Islands, U.S.",
        code: "VI",
    },
    {
        name: "Wyspy Heard i McDonalda",
        name_en: "Heard Island and McDonald Islands",
        code: "HM",
    },
    {
        name: "Wyspy Kokosowe",
        name_en: "Cocos (Keeling) Islands",
        code: "CC",
    },
    { name: "Wyspy Marshalla", name_en: "Marshall Islands", code: "MH" },
    { name: "Wyspy Owcze", name_en: "Faroe Islands", code: "FO" },
    { name: "Wyspy Salomona", name_en: "Solomon Islands", code: "SB" },
    {
        name: "Wyspy Świętego Tomasza i Książęca",
        name_en: "Sao Tome and Principe",
        code: "ST",
    },
    { name: "Zambia", name_en: "Zambia", code: "ZM" },
    { name: "Zimbabwe", name_en: "Zimbabwe", code: "ZW" },
    {
        name: "Zjednoczone Emiraty Arabskie",
        name_en: "United Arab Emirates",
        code: "AE",
    },
];
