import { StyleSheet } from "react-native";
import Colors from "../../../../constants/Colors";
export const styles = StyleSheet.create({
    footer: {
        height: 60,
        backgroundColor: "transparent",
        width: "100%",
    },
    wrapper: {
        flex: 1,
        alignItems: "center",
        backgroundColor: Colors.grayscale.surface.darker,
    },
    flatList: {
        width: "100%",
        justifyContent: "center",
        alignItems: "center",
    },
    darkShutter: {
        backgroundColor: Colors.grayscale.surface.darker,
        position: "absolute",
        bottom: -30,
        height: 600,
        left: 0,
        zIndex: -1,
        width: "120%",
    },
    sectionList: {
        justifyContent: "flex-start",
        width: "100%",
        backgroundColor: "transparent",
        alignItems: "center",
    },
    searchInput: {
        minHeight: 40,
    },
    switchDisplayedContentButton: {
        width: "50%",
        height: 32,
        fontSize: 12,
        color: Colors.grayscale.text.body,
        borderRadius: 4,
        fontFamily: "PoppinsSemiBold",
        paddingVertical: 6,
        paddingHorizontal: 24,
    },
    titleContainer: {
        marginBottom: 10,
        width: "100%",
        height: 44,
        flexDirection: "row",
        textAlign: "center",
        alignItems: "center",
        position: "relative",
    },
    backButton: {
        width: 44,
        height: 44,
        position: "absolute",
        top: 0,
        left: 0,
        backgroundColor: "transparent",
    },
    title: {
        fontSize: 10,
        width: "100%",
        textAlign: "center",
        color: Colors.grayscale.text.caption,
    },
    switchButtonsContainer: {
        display: "flex",
        flexDirection: "row",
        paddingTop: 4,
        paddingLeft: 4,
        paddingRight: 4,
        paddingBottom: 4,
        height: 40,
        alignItems: "center",
        backgroundColor: Colors.grayscale.surface.default,
        borderRadius: 8,
    },
    topBarContainer: {
        backgroundColor: Colors.grayscale.surface.darker,
        width: "100%",
        paddingTop: 8,
        paddingRight: 16,
        paddingLeft: 16,
        position: "relative",
        shadowOpacity: 0.15,
    },
    gradientStyle: {
        flex: 1,
        flexGrow: 1,
        justifyContent: "center",
        alignItems: "center",
    },
    flatListContainer: {
        width: "90%",
    },
    pickedText: {
        color: Colors.grayscale.text.body,
        fontFamily: "PoppinsSemiBold",
    },
    unpickedText: {
        color: Colors.grayscale.text.caption,
    },
    searchContainer: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        height: 60,
        width: "100%",
        paddingHorizontal: 16,
        backgroundColor: Colors.grayscale.surface.darker,
        marginTop: 0,
        paddingTop: 16,
        paddingBottom: 16,
        borderBottomLeftRadius: 24,
        borderBottomRightRadius: 24,
    },
    container: {
        flexGrow: 1,
        justifyContent: "center",
        alignItems: "center",
        overflow: "hidden",
        width: "100%",
    },
    stickyHeaderContainer: {
        backgroundColor: Colors.grayscale.surface.darker,
        borderBottomLeftRadius: 24,
        borderBottomRightRadius: 24,
    },
    searchIcon: {
        height: 44,
        width: 44,
        justifyContent: "flex-end",
        alignItems: "flex-end",
    },
    searchIconContainer: {
        width: "15%",
        justifyContent: "flex-end",
    },
    filterButton: { width: 44, height: 44 },
});
