import { StyleSheet } from "react-native";
import Colors from "../../../../constants/Colors";

export const styles = StyleSheet.create({
    backButton: {
        position: "absolute",
        width: 44,
        height: 44,
        top: 64,
        left: 16,
        zIndex: 1,
        backgroundColor: "transparent",
    },
    menuButton: {
        position: "absolute",
        width: 44,
        height: 44,
        top: 64,
        right: 16,
        zIndex: 1,
        backgroundColor: "transparent",
    },
    wrapper: {
        paddingTop: 32,
        paddingRight: 16,
        paddingLeft: 16,
    },
    bottomArea: {
        marginTop: 32,
        width: "100%",
        height: 72,
    },
    title: {
        marginTop: 44,
        fontSize: 12,
        width: "100%",
        textAlign: "center",
        color: Colors.grayscale.text.title,
    },
    mainAreaContainer: {
        flex: 1,
        width: "100%",
    },
    menuContainer: {
        position: "absolute",
        height: 112,
        backgroundColor: Colors.grayscale.surface.darker,
        borderWidth: 1,
        borderRadius: 12,
        borderColor: Colors.primary.surface.lighter,
        justifyContent: "space-between",
    },
    finishContainer: {
        borderBottomWidth: 1,
        borderBottomColor: Colors.grayscale.border.default,
        justifyContent: "space-between",
        flex: 1,
        paddingHorizontal: 16,
        flexDirection: "row",
        alignItems: "center",
    },
    finishorFinishText: {
        fontSize: 16,
        lineHeight: 19.2,
        color: Colors.grayscale.text.title,
    },
    shareContainer: {
        borderTopWidth: 1,
        flex: 1,
        paddingHorizontal: 16,
        borderTopColor: Colors.grayscale.border.default,
        justifyContent: "space-between",
        flexDirection: "row",
        alignItems: "center",
    },
    finishAdvertisementBackground: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "rgba(0, 0, 0, 0.5)",
    },
    finishAdvertisementContainer: {
        height: 216,
        width: "80%",
        backgroundColor: Colors.grayscale.surface.darker,
        borderWidth: 1,
        borderRadius: 24,
        borderColor: Colors.primary.surface.lighter,
        paddingHorizontal: 24,
        paddingVertical: 32,
        flexDirection: "column",
        justifyContent: "space-around",
        alignItems: "center",
    },
    finishTitle: {
        fontWeight: "bold",
        fontSize: 24,
        lineHeight: 28.8,
        color: Colors.grayscale.text.title,
    },
    finishSubtitle: {
        fontSize: 16,
        lineHeight: 19.2,
        color: Colors.grayscale.text.subtitle,
        textAlign: "center",
    },
    chooseButtonsContainer: {
        justifyContent: "space-between",
        flexDirection: "row",
        width: "100%",
    },
    chooseButton: { width: "48%" },
    blurViewBackground: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
    },
});
