import { StyleSheet } from "react-native";
import Colors from "../../../../constants/Colors";

export const styles = StyleSheet.create({
  socialNumberText: {
    fontSize: 20,
    lineHeight: 24,
    color: Colors.grayscale.text.title,
    fontFamily: "PoppinsSemiBold",
  },
  socialNameText: {
    fontSize: 10,
    lineHeight: 12,
    color: Colors.grayscale.text.body,
    textTransform: "capitalize",
  },
  socialNameWrapper: {
    flexDirection: "column",
    justifyContent: "space-between",
  },
  socialIconWrapper: {
    alignItems: "center",
    marginRight: 5,
    justifyContent: "center",
    flex: 1,
  },
  eachSocialPill: {
    flexDirection: "row",
    marginRight: 10,
  },
  influencerSocialsWrapper: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 24,
    flexDirection: "row",
  },
  influencerCategoriesScrollView: {
    alignItems: "center",
    marginBottom: 12,
    maxHeight: 40,
  },
  inviteInfluencerButton: {
    width: "100%",
    height: 56,
    borderWidth: 0,
    marginTop: 12,
    alignSelf: "flex-end",
    marginBottom: 24,
  },
  categoryName: {
    fontSize: 10,
    color: Colors.grayscale.text.body,
    textTransform: "capitalize",
  },
  eachInfluencerCategory: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    justifyContent: "center",
    alignItems: "center",
    minHeight: 4,
    borderRadius: 12,
    marginHorizontal: 2,
    marginVertical: 1,
    backgroundColor: Colors.grayscale.surface.subtle,
  },
  influencerCategoriesWrapper: {
    marginTop: 4,
    flexDirection: "row",
  },
  influencerInfoUsername: {
    color: Colors.grayscale.text.title,
    fontSize: 40,
    fontFamily: "PoppinsSemiBold",
  },
  influencerInfo: { marginTop: 54, flex: 1 },
  influencerSocialsBlurView: {
    width: "80%",
    height: 84,
    borderRadius: 24,
    borderColor: Colors.grayscale.surface.subtle,
    borderWidth: 1,
    zIndex: 1,
    position: "absolute",
    top: -42,
    alignSelf: "center",
  },
  influencerSocialsContainer: {
    height: "50%",
    width: "100%",
    position: "relative",
  },
  influencerPhotoGradient: {
    height: 120,
    width: "100%",
  },
  influencerPhoto: {
    width: "100%",
    height: "100%",
    borderTopLeftRadius: 48,
    borderTopRightRadius: 48,
    justifyContent: "flex-end",
    position: "relative",
  },
  influencerInfoPhotoContainer: {
    width: "100%",
    height: "50%",
    borderTopLeftRadius: 48,
    borderTopRightRadius: 48,
    overflow: "hidden",
    justifyContent: "flex-end",
  },
  influencerInfoContainer: {
    width: "100%",
    height: "100%",
    backgroundColor: Colors.grayscale.surface.darker,
    borderTopLeftRadius: 48,
    borderTopRightRadius: 48,
  },
  influencerName: {
    fontSize: 12,
    lineHeight: 17.8,
  },
  influencerUsername: {
    fontSize: 16,
    fontFamily: "PoppinsSemiBold",
    lineHeight: 19.2,
  },
  influencerNamesContainer: {
    flexDirection: "column",
    justifyContent: "space-between",
    height: 36,
  },
  userAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    marginRight: 16,
    overflow: "hidden",
  },
  userRow: {
    width: "100%",
    height: 36,
    flexDirection: "row",
  },
  infoText: {
    fontSize: 12,
    color: Colors.grayscale.text.subtitle,
    marginTop: 12,
    width: "100%",
  },
  subtitle: {
    fontSize: 12,
    color: Colors.grayscale.text.subtitle,
    marginBottom: 12,
  },
  flatListContainer: { width: "100%" },
});
